Lots of changes for Debian package... see changelog for details.
git-svn-id: svn://svn.freevo.org/freevo/trunk/freevo@4778 cc3e1ea1-1e01-0410-8d68-8b121e83a9d5

diff --git a/contrib/debian/rules b/contrib/debian/rules
--- a/contrib/debian/rules
+++ b/contrib/debian/rules
@@ -25,9 +25,9 @@ clean:
 	-python2.3 setup.py clean
 	rm -f `find . | grep freevo.mo`
 	rm -rf src/www/htdocs/help/wiki
-	rm -f `pwd`/src/util/distutils.pyc
-	rm -f `pwd`/src/util/__init__.pyc
-	rm -f `pwd`/src/version.pyc
+	rm -f $(CURDIR)/src/util/distutils.pyc
+	rm -f $(CURDIR)/src/util/__init__.pyc
+	rm -f $(CURDIR)/src/version.pyc
 	rm -f *.pyc
 	rm -fr build
 	rm -f Setup
@@ -38,17 +38,17 @@ install: build
 	dh_testroot
 	dh_clean -k
 	dh_installdirs
-	./autogen.sh nodocs
-	python2.3 setup.py install --no-compile --root=`pwd`/debian/freevo
+	$(CURDIR)/autogen.sh nodocs
+	python2.3 setup.py install --no-compile --root=$(CURDIR)/debian/tmp
+	# Clean up warnings
+	rm $(CURDIR)/debian/tmp/usr/lib/python2.3/site-packages/freevo/plugins/mixer.py
+
+	cat $(CURDIR)/debian/bsd-ioctl-remove.diff | patch -p0 -E
 	# Move the files in to the data package
-	mv `pwd`/debian/freevo/usr/share/freevo/fonts  `pwd`/debian/freevo-media/usr/share/freevo/
-	mv `pwd`/debian/freevo/usr/share/freevo/icons  `pwd`/debian/freevo-media/usr/share/freevo/
-	mv `pwd`/debian/freevo/usr/share/freevo/images `pwd`/debian/freevo-media/usr/share/freevo/
-	mv `pwd`/debian/freevo/usr/share/freevo/skins  `pwd`/debian/freevo-media/usr/share/freevo/
-	mkdir -p `pwd`/debian/freevo/usr/share/freevo/init/ || true
-	cp `pwd`/boot/webserver_init		       `pwd`/debian/freevo/usr/share/freevo/init/
-	cp `pwd`/boot/recordserver_init		       `pwd`/debian/freevo/usr/share/freevo/init/
-	echo 'FREEVO_HOME="/usr/bin"'	>	`pwd`/debian/freevo/etc/freevo/boot_config
+	mkdir -p $(CURDIR)/debian/freevo/usr/share/freevo/init/ || true
+	cp $(CURDIR)/boot/webserver_init		       $(CURDIR)/debian/freevo/usr/share/freevo/init/
+	cp $(CURDIR)/boot/recordserver_init		       $(CURDIR)/debian/freevo/usr/share/freevo/init/
+	echo 'FREEVO_HOME="/usr/bin"'	>	$(CURDIR)/debian/freevo/etc/freevo/boot_config
     
 # Build architecture-independent files here.
 binary-indep: build install
@@ -64,6 +64,7 @@ doclist = $(filter-out docs/util docs/fullinstall.txt docs/LGPL,$(wildcard docs/
 binary-arch: build install
 	dh_testdir
 	dh_testroot
+	dh_install --autodest --sourcedir=debian/tmp
 	dh_installdocs $(doclist)
 	dh_installmenu
 	dh_installchangelogs 
